### ISSUE TITLE
查询失败一直在重复。

### ISSUE THREAD

**Issue by gdft2112** [a1most/disu#5]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/37747628/195996803-27359427-8957-4816-9e90-f28e5180c188.png">

**Comment by gdft2112** [comment]
另外fofa加了key默认查询一百
<img width="640" alt="image" src="https://user-images.githubusercontent.com/37747628/195997565-6494b1c2-62b5-49d5-989e-0c48bba1bad4.png">

**Comment by a1most** [comment]
第一个截图是正常的，因为shopee.tw有1千多条子域名信息，dnsscan每次只能获取20条数据，所以会有1000+/20次请求，但是每次请求报错信息没有区分，所以看上去是一直在循环。针对这里已经优化输出信息，每一次请求的报错会区分开来。
第二个截图由于没有指定size，所以默认查询100，目前已经设定为10000的数值。
