### ISSUE TITLE
提个需求，我希望可以直接outfile txt文件，里面只有域名的那种。

### ISSUE THREAD

**Issue by gdft2112** [a1most/disu#6]
如题，不然每次还要下载再复制粘贴到服务器。

**Comment by a1most** [comment]
给我你的邮箱，我给你发一个，输出到txt文件的版本。

**Comment by gdft2112** [comment]
我的邮箱是karokirkland@gmail.com

**Comment by a1most** [comment]
[disu-main.zip](https://github.com/a1most/disu/files/9845644/disu-main.zip)
